# -*- coding: utf-8 -*-
"""
Static assets must never go stale against fresh markup.

The failure this prevents: index.html is generated by a route and always
fresh, while app.js and style.css came from StaticFiles, which sends ETag and
Last-Modified but no Cache-Control. Browsers read that absence as permission to
reuse without asking, so a reloaded page ran an old script against markup whose
element ids had changed — and threw on the first getElementById returning null.
"""

import os
import re
import sys
import time
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
os.environ.setdefault("EMBEDDING_PROVIDER", "hash")

from fastapi.testclient import TestClient  # noqa: E402

from backend.server import app  # noqa: E402

client = TestClient(app)

ASSETS = ["style.css", "app.js"]


def test_static_assets_must_be_revalidated():
    for name in ASSETS:
        resp = client.get("/static/%s" % name)
        assert resp.status_code == 200, name
        cache = resp.headers.get("cache-control", "")
        assert "no-cache" in cache, "%s served without no-cache: %r" % (name, cache)


def test_index_is_never_stored():
    resp = client.get("/")
    assert resp.status_code == 200
    assert "no-store" in resp.headers.get("cache-control", "")


@pytest.mark.parametrize("name", ASSETS)
def test_asset_urls_are_version_stamped(name):
    html = client.get("/").text
    matches = re.findall(r"/static/%s\?v=([0-9a-f]+-[0-9a-f]+)" % re.escape(name), html)
    assert matches, "%s is linked without a version stamp" % name
    # ...and the stamped URL must actually serve.
    assert client.get("/static/%s?v=%s" % (name, matches[0])).status_code == 200


def test_editing_an_asset_changes_its_stamp(tmp_path):
    """A changed file must produce a different URL, or caching can still skew."""
    from backend.server import STATIC_DIR, _asset_stamp

    target = STATIC_DIR / "app.js"
    before = _asset_stamp("app.js")
    original = target.read_bytes()
    try:
        # Bump mtime by a second; the stamp has one-second resolution.
        os.utime(str(target), (time.time() + 5, time.time() + 5))
        assert _asset_stamp("app.js") != before
    finally:
        target.write_bytes(original)


def test_a_missing_asset_stamps_without_raising():
    from backend.server import _asset_stamp
    assert _asset_stamp("does-not-exist.js") == "0"


def test_every_static_reference_in_the_markup_resolves():
    """Catch a renamed or deleted asset that the template still points at."""
    html = Path(ROOT / "frontend" / "templates" / "index.html").read_text(encoding="utf-8")
    for ref in set(re.findall(r'(?:href|src)="(/static/[^"?]+)', html)):
        assert client.get(ref).status_code == 200, ref
